### ISSUE TITLE
Less harsh defaults for plots

### ISSUE THREAD

**Issue by Datseris** [fbanning/OSMMakie.jl#8]
Current defaults look like this:

![image](https://user-images.githubusercontent.com/19669089/149426235-063b20f5-676e-4b74-9389-365c7dee3184.png)

I think it would be nice to use a less harsh color for larger roads instead of this thick black. Some reds, oranges, and yellows will make a for a more pleasant map maybe? 

e.g., 

![image](https://user-images.githubusercontent.com/19669089/149426329-4fbab89b-1d2f-4555-bcbf-6892a03cbdf2.png)

(p.s.: it is not clear from the docs how to change these defaults via keywords to `osmplot!`)

**Comment by fbanning** [comment]
Yes, thanks for the suggestion. I have this on the list and it is currently the last remaining to-do for #4.

I haven't yet found the time to look at standard colour schemes for OpenStreetMap. The streets on www.openstreetmap.org only vary by width and not by colour. They reserve colours for marking areas, e.g. forests, public parks or historic building areas.

Because OSMMakie currently doesn't support plotting building polys and fenced areas, I've added the todo mentioned above. Simply colouring the streets according to their street type should be fine for now.

> (p.s.: it is not clear from the docs how to change these defaults via keywords to osmplot!)

You can manually color the streets to your liking via the `edge_color` keyword used in graphplot.
Documentation for `edge_color` can be found [here](https://juliaplots.org/GraphMakie.jl/stable/#GraphMakie.graphplot).
It takes either a single colour (e.g. `:red` or a `color""` or whatever) or you can provide it a vector of colours where each index corresponds to the index of the graph edge.

It is possible to pass `edge_color` (and all other `graphplot` keyword arguments) on through `osmplot!` if you use the `graphplotkwargs` kwarg and pass it a NamedTuple of the kwargs you want to pass on to graphplot.

**Comment by Datseris** [comment]
> You can manually color the streets to your liking via the edge_color keyword used in graphplot.

But I don't want to be choosing a color for each individual street; as you said, I'd rather color streets by their type. For standard road, only pedestrian, and highways

**Comment by fbanning** [comment]
I thought you're asking about how to adapt the plot attributes to a user's needs. That's why I gave the explanation about `edge_color`.

The defaults are defined via separate functions in `src/defaults.jl`. As I said: it's on my list to colour them accordingly to way type (see #4 ).

**Comment by Datseris** [comment]
Yeah, sorry I wasn't clear. It may be convenient to allow the user to pass a dictionary to `osmplot!` (or to propagate keyword arguments) so that the user can decide the color of the street types instead of the individual edges.

**Comment by fbanning** [comment]
> It may be convenient to allow the user to pass a dictionary to `osmplot!` so that the user can decide the color of the street types

That's a good idea! Definitely putting that on the list for v0.2.0. :)
